In [111]:
import os
import sys
import pickle
from inspect import signature

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
import sklearn.metrics as metrics

get_dir = os.path.dirname
PROJ_ROOT = get_dir(get_dir(os.path.abspath('__file__')))
print(PROJ_ROOT)
sys.path.append(os.path.join(PROJ_ROOT, 'src'))

from data import dataset

C:\Users\48519\Professional Stuff\various\machine_learning\mouse_disambiguation


In [112]:
FEATURES_PATH = dataset.DEFAULT_FEATURES_DIRECTORY
TRAIN_FEATURES_PATH = os.path.join(FEATURES_PATH, 'train.npy')
data = np.load(TRAIN_FEATURES_PATH, allow_pickle=True)
data



array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [113]:
# Okay, lets try fitting a Logistic Regression
lr = LogisticRegression(solver='liblinear', class_weight='balanced', C=0.00001)
features, classes = data[:,:-1], data[:,-1] 
lr.fit(features, classes)
prediction = lr.predict(features)
print('TRAIN ACCURACY: {}, Precision: {}, Recall: {}'.format(
    metrics.accuracy_score(classes, prediction),
    metrics.precision_score(classes, prediction),
    metrics.recall_score(classes, prediction)
))

TRAIN ACCURACY: 0.985981308411215, Precision: 1.0, Recall: 0.98125


In [114]:
# load validation
VALIDATION_FEATURES_PATH = os.path.join(FEATURES_PATH, 'validation.npy')
validaton = np.load(VALIDATION_FEATURES_PATH, allow_pickle=True)
v_features, v_classes = validaton[:,:-1], validaton[:,-1]
v_prediction = lr.predict(v_features)

print('VALIDATION ACCURACY: {}, Precision: {}, Recall: {}'.format(
    metrics.accuracy_score(v_classes, v_prediction),
    metrics.precision_score(v_classes, v_prediction),
    metrics.recall_score(v_classes, v_prediction)
))

metrics.confusion_matrix(v_classes, v_prediction)

VALIDATION ACCURACY: 0.9154929577464789, Precision: 0.9318181818181818, Recall: 0.9318181818181818


array([[24,  3],
       [ 3, 41]], dtype=int64)

In [115]:

print('VALIDATION ACCURACY: {}, Precision: {}, Recall: {}'.format(
    metrics.accuracy_score(v_classes, v_prediction),
    metrics.precision_score(v_classes, v_prediction),
    metrics.recall_score(v_classes, v_prediction)
))

print('VALIDATION ACCURACY: {}, Precision: {}, Recall: {}'.format(
    metrics.accuracy_score(v_classes, v_prediction),
    metrics.precision_score(v_classes, v_prediction),
    metrics.recall_score(v_classes, v_prediction)
))

metrics.confusion_matrix(v_classes, v_prediction)


VALIDATION ACCURACY: 0.9154929577464789, Precision: 0.9318181818181818, Recall: 0.9318181818181818
VALIDATION ACCURACY: 0.9154929577464789, Precision: 0.9318181818181818, Recall: 0.9318181818181818


array([[24,  3],
       [ 3, 41]], dtype=int64)